from telegram.error import BadRequest


def badrequest(update, context, exception: BadRequest):
    pass
